---
title: "Students_Grades_Prediction_Decision_Tree"
output: html_document
---

# attaching relevant libraries
```{r}
library(dplyr)
library(tree)
library(caret)
```


```{r}
grades <- read.csv("xAPI-Edu-Data.csv", stringsAsFactors = T)
grades$Class <- factor(grades$Class, levels = c("L", "M", "H"))
head(grades, 10)
```

# Decision Tree ~ all features
```{r}
#Data Preparation
RNGkind(sample.kind = "Rounding")
set.seed(123)
sample_index <- sample(1:nrow(grades), size = floor(0.70*nrow(grades)), replace = F)
train <- grades[sample_index,]
test <- grades[-sample_index,]
grades_actual <- test$Class
dim(train)
```

```{r}
#create the tree
tree_grades <- tree(Class~., train)
summary(tree_grades)
plot(tree_grades)
title("Regression Tree to Predict Class Grades")
text(tree_grades, pretty=0)

#performance measurement
predict_grades1 <- predict(tree_grades, newdata=test, type="class")
grades_actual <- test$Class
confusionMatrix(predict_grades1, grades_actual, mode='everything')
```

```{r}
#prune the tree using cross-validation
cv_grades <- cv.tree(tree_grades, FUN=prune.misclass)
optimal_nodes <- cv_grades$size[which.min(cv_grades$dev)]
prune_grades <- prune.misclass(tree_grades, best = optimal_nodes)
summary(prune_grades)
plot(prune_grades)
title("Pruned Tree to Predict Class Grades")
text(prune_grades, pretty=0)

#performance measurement
predict_grades2 <- predict(prune_grades, newdata=test, type="class")
confusionMatrix(predict_grades2, grades_actual, mode='everything')
```

# Decision Tree ~ StudentAbsenceDays, raisedhands, VisITedResources, AnnouncementsView, Discussion, Relation, PlaceofBirth, Topic, GradeID
```{r}
#Data Preparation
grades_f1 <- grades %>%
  dplyr::select(StudentAbsenceDays, raisedhands, VisITedResources, AnnouncementsView, Discussion, Relation, PlaceofBirth, Topic, GradeID, Class)

head(grades_f1)
```

```{r}
#sample data 70%
RNGkind(sample.kind = "Rounding")
set.seed(123)
sample_index <- sample(1:nrow(grades_f1), size = floor(0.70*nrow(grades_f1)), replace = F)
trainf1 <- grades_f1[sample_index,]
testf1 <- grades_f1[-sample_index,]
```


```{r}
#create the tree
tree_gradesf1 <- tree(Class~., trainf1)
summary(tree_gradesf1)
plot(tree_grades)
title("Regression Tree to Predict Class Grades")
text(tree_gradesf1, pretty=0)

#prune the tree using cross-validation
cv_gradesf1 <- cv.tree(tree_gradesf1, FUN=prune.misclass)
optimal_nodesf1 <- cv_gradesf1$size[which.min(cv_gradesf1$dev)]
prune_gradesf1 <- prune.misclass(tree_gradesf1, best = optimal_nodesf1)
summary(prune_gradesf1)
plot(prune_gradesf1)
title("Pruned Tree to Predict Class Grades")
text(prune_gradesf1, pretty=0)

#performance measurement
predict_gradesf1 <- predict(prune_gradesf1, newdata=testf1, type="class")
grades_actualf1 <- testf1$Class
confusionMatrix(predict_gradesf1, grades_actualf1, mode='everything')
```